/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import DAO.professorDAO;
import models.Professor;

/**
 *
 * @author hélio
 */
public class telaProfessor extends javax.swing.JFrame {

    /**
     * Creates new form telaProfessor
     */
    int idProfessor;
    public telaProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        lblDisciplina = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        btnListagemTarefas = new javax.swing.JButton();
        btnAlterarNota = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taComunicados = new javax.swing.JTextArea();
        btPublicarTarefa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(251, 251, 251));
        jPanel5.setPreferredSize(new java.awt.Dimension(477, 250));
        jPanel5.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(9, 20, 137));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Source Serif Pro", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Página do Professor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 85);

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/foto (1).png"))); // NOI18N
        jPanel5.add(foto);
        foto.setBounds(0, 80, 100, 90);

        lblDisciplina.setBackground(new java.awt.Color(44, 56, 98));
        lblDisciplina.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lblDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        lblDisciplina.setText("Disciplina");
        lblDisciplina.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblDisciplina.setOpaque(true);
        jPanel5.add(lblDisciplina);
        lblDisciplina.setBounds(100, 130, 190, 27);

        lblTitulo.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Comunicados:");
        jPanel5.add(lblTitulo);
        lblTitulo.setBounds(10, 200, 120, 25);

        lblNome.setBackground(new java.awt.Color(44, 56, 98));
        lblNome.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome");
        lblNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblNome.setOpaque(true);
        jPanel5.add(lblNome);
        lblNome.setBounds(100, 90, 310, 27);

        btnListagemTarefas.setBackground(new java.awt.Color(9, 24, 77));
        btnListagemTarefas.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnListagemTarefas.setForeground(new java.awt.Color(255, 255, 255));
        btnListagemTarefas.setText("Listagem de Tarefas");
        btnListagemTarefas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnListagemTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListagemTarefasActionPerformed(evt);
            }
        });
        jPanel5.add(btnListagemTarefas);
        btnListagemTarefas.setBounds(290, 380, 190, 40);

        btnAlterarNota.setBackground(new java.awt.Color(9, 24, 77));
        btnAlterarNota.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnAlterarNota.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarNota.setText("Alterar Notas");
        btnAlterarNota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAlterarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarNotaActionPerformed(evt);
            }
        });
        jPanel5.add(btnAlterarNota);
        btnAlterarNota.setBounds(290, 260, 190, 40);

        taComunicados.setBackground(new java.awt.Color(204, 204, 204));
        taComunicados.setColumns(20);
        taComunicados.setFont(new java.awt.Font("Source Serif Pro", 0, 14)); // NOI18N
        taComunicados.setForeground(new java.awt.Color(0, 0, 0));
        taComunicados.setLineWrap(true);
        taComunicados.setRows(5);
        taComunicados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        taComunicados.setSelectionColor(new java.awt.Color(51, 153, 255));
        jScrollPane1.setViewportView(taComunicados);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 260, 250);

        btPublicarTarefa.setBackground(new java.awt.Color(9, 24, 77));
        btPublicarTarefa.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btPublicarTarefa.setForeground(new java.awt.Color(255, 255, 255));
        btPublicarTarefa.setText("Publicar Tarefa");
        btPublicarTarefa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btPublicarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPublicarTarefaActionPerformed(evt);
            }
        });
        jPanel5.add(btPublicarTarefa);
        btPublicarTarefa.setBounds(290, 320, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarNotaActionPerformed
        telaAlterarNota tl = new telaAlterarNota();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAlterarNotaActionPerformed

    private void btnListagemTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListagemTarefasActionPerformed
        listagemTarefas lt = new listagemTarefas();
        lt.setVisible(true);
        lt.atualizarTabela();
        lt.id = idProfessor;
        this.dispose();

    }//GEN-LAST:event_btnListagemTarefasActionPerformed

    private void btPublicarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPublicarTarefaActionPerformed
        telaPublicarTarefa tpt = new telaPublicarTarefa();
        tpt.setVisible(true);
        this.dispose();
        tpt.id = idProfessor;
    }//GEN-LAST:event_btPublicarTarefaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPublicarTarefa;
    private javax.swing.JButton btnAlterarNota;
    private javax.swing.JButton btnListagemTarefas;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDisciplina;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea taComunicados;
    // End of variables declaration//GEN-END:variables
    
    public void getProfessor(int id){
        professorDAO dao = new professorDAO();
        Professor p = dao.buscar(id);
        idProfessor = p.getId();
        lblNome.setText(p.getNome());
        lblDisciplina.setText(p.getDisciplina());
        taComunicados.setText(p.getComunicado());
    }

}
