/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import DAO.alunoDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Aluno;
import models.tarefa;

/**
 *
 * @author hélio
 */
public class telaAluno extends javax.swing.JFrame {

    /**
     * Creates new form telaAluno
     */
    
    private String[] colunas = {"Tarefa", "Data De entrega", "descricao", "turma", "professor"};
    
    DefaultTableModel mt = new DefaultTableModel(colunas, 0);
    
    int id;
    Aluno aluno;
    
    public telaAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Foto = new javax.swing.JLabel();
        lblTurma = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblTarefasPendentes = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(251, 251, 251));
        jPanel5.setPreferredSize(new java.awt.Dimension(477, 250));
        jPanel5.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(9, 20, 137));

        jLabel1.setFont(new java.awt.Font("Source Serif Pro", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Página do Aluno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel1);
        jPanel1.setBounds(0, 0, 477, 85);

        Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/foto (1).png"))); // NOI18N
        jPanel5.add(Foto);
        Foto.setBounds(0, 80, 100, 90);

        lblTurma.setBackground(new java.awt.Color(44, 56, 98));
        lblTurma.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lblTurma.setForeground(new java.awt.Color(255, 255, 255));
        lblTurma.setText("Turma");
        lblTurma.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblTurma.setOpaque(true);
        jPanel5.add(lblTurma);
        lblTurma.setBounds(100, 130, 190, 27);

        lblNome.setBackground(new java.awt.Color(44, 56, 98));
        lblNome.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome");
        lblNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblNome.setOpaque(true);
        jPanel5.add(lblNome);
        lblNome.setBounds(100, 90, 310, 27);

        lblTarefasPendentes.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lblTarefasPendentes.setForeground(new java.awt.Color(0, 0, 0));
        lblTarefasPendentes.setText("Tarefas Pendentes");
        jPanel5.add(lblTarefasPendentes);
        lblTarefasPendentes.setBounds(160, 230, 160, 25);

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(9, 24, 77));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tabela.setFont(new java.awt.Font("Source Serif Pro", 0, 12)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Disciplina", "Data de Entrega", "Descrição", "Turma", "Professor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTarefasPendentes;
    private javax.swing.JLabel lblTurma;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
    
    public void getAluno(int id){
        alunoDAO d = new alunoDAO();
        aluno = d.buscar(id);
        
        lblNome.setText(aluno.getNome());
        lblTurma.setText(Integer.toString(aluno.getTurma()));
        atualizaTarefas(aluno.getTurma());
    }
    
    
    public void atualizaTarefas(int turma){
        alunoDAO d = new alunoDAO();
        List <tarefa> lista = d.listarTarefasId(turma);
        tarefa t;
        mt = new DefaultTableModel(colunas, 0);
         
        for(int i = 0; i < lista.size(); i++){
             
            t = lista.get(i);
            String[] row = {
                t.getNome(), t.getData_entrega(), t.getDescricao(), Integer.toString(t.getTurma()), t.getProfessor()
            };
            mt.addRow(row);
        }
        tabela.setModel(mt);
    }
    

}
